### ISSUE TITLE
(!) sync. Firmwaretests hängen in test_Server_2.py

### ISSUE THREAD

**Issue by P8H** [PumucklOnTheAir/TestFramework#183]
Symptome:
Manche Testausführungen weisen darauf hin, dass die Testfirmware manchmal ein Timeout erzeugen.

Reproduktion:
'while python3 -m pytest framework_unittests/test_A_Server_2.py; sleep 2; do echo; done' 
die meisten Tests sind innerhalb von 30ms fertig, einige wenige brauchen 330ms. Ein Hinweis, dass ein Test durch ein Timeout beendet wurde.

**Comment by P8H** [comment]
in der Branch exception-handling-#105 wurde der Server und der Test test_A_Server_2.py verbessert, um die TimeOut Fehler zu detektieren.

Fazit bei bisherigen Tests:
Alle Testausführungen ergaben ein "multiprocessing.context.TimeoutError".
Lediglich der Zeitpunkt ist unterschiedlich.
Nach 12 Ausführungen...
3
2
16
5



======================================================================== FAILURES ========================================================================
___________________________________________________________ ServerTestCase2.test_test_results ____________________________________________________________

self = <test_A_Server_2.ServerTestCase2 testMethod=test_test_results>

    def tearDown(self):
>       assert not len(self.server_proxy.get_task_errors())  # check if an error happens
E       AssertionError: assert not 1
E        +  where 1 = len([(0, ("<class 'multiprocessing.context.TimeoutError'>", '', '<traceback object at 0xb5a66af8>'))])
E        +    where [(0, ("<class 'multiprocessing.context.TimeoutError'>", '', '<traceback object at 0xb5a66af8>'))] = <bound method get_task_errors of <AutoProxy[get_server_proxy] object, typeid 'get_server_proxy' at 0xb5a4e350>>()
E        +      where <bound method get_task_errors of <AutoProxy[get_server_proxy] object, typeid 'get_server_proxy' at 0xb5a4e350>> = <AutoProxy[get_server_proxy] object, typeid 'get_server_proxy' at 0xb5a4e350>.get_task_errors
E        +        where <AutoProxy[get_server_proxy] object, typeid 'get_server_proxy' at 0xb5a4e350> = <test_A_Server_2.ServerTestCase2 testMethod=test_test_results>.server_proxy

framework_unittests/test_A_Server_2.py:56: AssertionError
------------------------------------------------------------------ Captured stdout call ------------------------------------------------------------------
......................................................................................................................................................
------------------------------------------------------------------ Captured stderr call ------------------------------------------------------------------
Process ForkPoolWorker-1:4:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/usr/local/lib/python3.5/multiprocessing/queues.py", line 345, in get
    return ForkingPickler.loads(res)
AttributeError: Can't get attribute 'ConnectionTest' on <module 'firmware_tests.demo_1' from '/root/TestFramework_kevin/firmware_tests/demo_1.py'>
_____________________________________________________________ ServerTestCase2.test_test_set ______________________________________________________________

self = <test_A_Server_2.ServerTestCase2 testMethod=test_test_set>

    def tearDown(self):
>       assert not len(self.server_proxy.get_task_errors())  # check if an error happens
E       AssertionError: assert not 1
E        +  where 1 = len([(0, ("<class 'multiprocessing.context.TimeoutError'>", '', '<traceback object at 0xb5a66af8>'))])
E        +    where [(0, ("<class 'multiprocessing.context.TimeoutError'>", '', '<traceback object at 0xb5a66af8>'))] = <bound method get_task_errors of <AutoProxy[get_server_proxy] object, typeid 'get_server_proxy' at 0xb5a4e590>>()
E        +      where <bound method get_task_errors of <AutoProxy[get_server_proxy] object, typeid 'get_server_proxy' at 0xb5a4e590>> = <AutoProxy[get_server_proxy] object, typeid 'get_server_proxy' at 0xb5a4e590>.get_task_errors
E        +        where <AutoProxy[get_server_proxy] object, typeid 'get_server_proxy' at 0xb5a4e590> = <test_A_Server_2.ServerTestCase2 testMethod=test_test_set>.server_proxy

framework_unittests/test_A_Server_2.py:56: AssertionError
------------------------------------------------------------------ Captured stdout call ------------------------------------------------------------------
PING localhost (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_req=1 ttl=64 time=0.284 ms

--- localhost ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.284/0.284/0.284/0.000 ms
..PING localhost (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_req=1 ttl=64 time=0.276 ms

--- localhost ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.276/0.276/0.276/0.000 ms
..
========================================================== 2 failed, 2 passed in 331.50 seconds ==========================================================

**Comment by P8H** [comment]
der Inhalt der Firmwaretests scheint nicht der Grund zu sein. Weder time.sleep() noch os.system(ping) machen ein unterschied.

**Comment by P8H** [comment]
scheint abhängig zu sein von der blockierten Ausführung + mehrere Tests in einem Set.
