### ISSUE TITLE
Runtime Server startet, obwohl fatale Fehler auftreten

### ISSUE THREAD

**Issue by mweinelt** [PumucklOnTheAir/TestFramework#88]
Wenn ich den Server unpriviligert starte kommt es zu fatalen Fehlern. Der Fehler sollte entweder gefangen werden, oder der Server nicht starten, wenn man nicht root ist.

```
$ source ~/.venv/Testframework/bin/activate
$ ./start_server.py                        
2016-01-26 00:47:23,084 - INFO     : 	Update the Infos of the Router(0) ...
2016-01-26 00:47:23,084 - INFO     : 	Create Network Controller ...
2016-01-26 00:47:23,196 - DEBUG    : 		Create VLAN Interface ...
2016-01-26 00:47:23,197 - DEBUG    : 			[-] vlan21 couldn't be created
2016-01-26 00:47:23,197 - ERROR    : 			'eth0'
2016-01-26 00:47:23,197 - DEBUG    : 		Create Namespace ...
2016-01-26 00:47:23,202 - DEBUG    : 			[-] Couldn't create Namespace(nsp21)
2016-01-26 00:47:23,205 - ERROR    : 			  File "/home/hexa/tmp/TestFramework/network/namespace.py", line 28, in __init__
    self.ipdb_netns = IPDB(nl=NetNS(nsp_name))

2016-01-26 00:47:23,205 - ERROR    : 			  File "/home/hexa/.venv/Testframework/lib/python3.5/site-packages/pyroute2/netns/nslink.py", line 190, in __init__
    super(NetNS, self).__init__()

2016-01-26 00:47:23,205 - ERROR    : 			  File "/home/hexa/.venv/Testframework/lib/python3.5/site-packages/pyroute2/netlink/nlsocket.py", line 279, in __init__
    super(NetlinkMixin, self).__init__()

2016-01-26 00:47:23,205 - ERROR    : 			  File "/home/hexa/.venv/Testframework/lib/python3.5/site-packages/pyroute2/remote/__init__.py", line 206, in __init__
    raise init['error']

2016-01-26 00:47:23,206 - ERROR    : 			[Errno 13] Permission denied: b'/var/run/netns'
2016-01-26 00:47:23,206 - DEBUG    : 		Delete Namespace ...
2016-01-26 00:47:23,206 - DEBUG    : 			[+] Namespace(nsp21) is already deleted
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/hexa/tmp/TestFramework/util/router_info.py", line 60, in run
    network_ctrl = NetworkCtrl(self.router, 'eth0')
  File "/home/hexa/tmp/TestFramework/network/network_ctrl.py", line 44, in __init__
    int(self.remote_system.vlan_iface_id))
  File "/home/hexa/tmp/TestFramework/network/nv_assist.py", line 46, in create_namespace_vlan
    self.namespace.encapsulate_interface(self.vlan.vlan_iface_name)
  File "/home/hexa/tmp/TestFramework/network/namespace.py", line 65, in encapsulate_interface
    self.vlan_iface_ip = self._get_ipv4_from_dictionary(self.ipdb.interfaces[self.vlan_iface_name])
KeyError: 'vlan21'

Runtime Server started
```

**Comment by P8H** [comment]
Umgesetzt in der Branch testbasic-#3. Im Server.start folgendes hinzugefügt:

if not os.geteuid() == 0:
    sys.exit('Script must be run as root')
